/*------------------------------------------------------------------------------
//   This code was generated by template ffi.go.tmpl.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "ffi.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/
package ffi

//revive:disable

var (
	api GDExtensionInterface
)

type GDExtensionInterface struct {
	// All of the GDExtension interface functions.
	GetProcAddress GDExtensionInterfaceGetProcAddress
	GetGodotVersion GDExtensionInterfaceGetGodotVersion
	MemAlloc GDExtensionInterfaceMemAlloc
	MemRealloc GDExtensionInterfaceMemRealloc
	MemFree GDExtensionInterfaceMemFree
	PrintError GDExtensionInterfacePrintError
	PrintErrorWithMessage GDExtensionInterfacePrintErrorWithMessage
	PrintWarning GDExtensionInterfacePrintWarning
	PrintWarningWithMessage GDExtensionInterfacePrintWarningWithMessage
	PrintScriptError GDExtensionInterfacePrintScriptError
	PrintScriptErrorWithMessage GDExtensionInterfacePrintScriptErrorWithMessage
	GetNativeStructSize GDExtensionInterfaceGetNativeStructSize
	VariantNewCopy GDExtensionInterfaceVariantNewCopy
	VariantNewNil GDExtensionInterfaceVariantNewNil
	VariantDestroy GDExtensionInterfaceVariantDestroy
	VariantCall GDExtensionInterfaceVariantCall
	VariantCallStatic GDExtensionInterfaceVariantCallStatic
	VariantEvaluate GDExtensionInterfaceVariantEvaluate
	VariantSet GDExtensionInterfaceVariantSet
	VariantSetNamed GDExtensionInterfaceVariantSetNamed
	VariantSetKeyed GDExtensionInterfaceVariantSetKeyed
	VariantSetIndexed GDExtensionInterfaceVariantSetIndexed
	VariantGet GDExtensionInterfaceVariantGet
	VariantGetNamed GDExtensionInterfaceVariantGetNamed
	VariantGetKeyed GDExtensionInterfaceVariantGetKeyed
	VariantGetIndexed GDExtensionInterfaceVariantGetIndexed
	VariantIterInit GDExtensionInterfaceVariantIterInit
	VariantIterNext GDExtensionInterfaceVariantIterNext
	VariantIterGet GDExtensionInterfaceVariantIterGet
	VariantHash GDExtensionInterfaceVariantHash
	VariantRecursiveHash GDExtensionInterfaceVariantRecursiveHash
	VariantHashCompare GDExtensionInterfaceVariantHashCompare
	VariantBooleanize GDExtensionInterfaceVariantBooleanize
	VariantDuplicate GDExtensionInterfaceVariantDuplicate
	VariantStringify GDExtensionInterfaceVariantStringify
	VariantGetType GDExtensionInterfaceVariantGetType
	VariantHasMethod GDExtensionInterfaceVariantHasMethod
	VariantHasMember GDExtensionInterfaceVariantHasMember
	VariantHasKey GDExtensionInterfaceVariantHasKey
	VariantGetTypeName GDExtensionInterfaceVariantGetTypeName
	VariantCanConvert GDExtensionInterfaceVariantCanConvert
	VariantCanConvertStrict GDExtensionInterfaceVariantCanConvertStrict
	GetVariantFromTypeConstructor GDExtensionInterfaceGetVariantFromTypeConstructor
	GetVariantToTypeConstructor GDExtensionInterfaceGetVariantToTypeConstructor
	VariantGetPtrOperatorEvaluator GDExtensionInterfaceVariantGetPtrOperatorEvaluator
	VariantGetPtrBuiltinMethod GDExtensionInterfaceVariantGetPtrBuiltinMethod
	VariantGetPtrConstructor GDExtensionInterfaceVariantGetPtrConstructor
	VariantGetPtrDestructor GDExtensionInterfaceVariantGetPtrDestructor
	VariantConstruct GDExtensionInterfaceVariantConstruct
	VariantGetPtrSetter GDExtensionInterfaceVariantGetPtrSetter
	VariantGetPtrGetter GDExtensionInterfaceVariantGetPtrGetter
	VariantGetPtrIndexedSetter GDExtensionInterfaceVariantGetPtrIndexedSetter
	VariantGetPtrIndexedGetter GDExtensionInterfaceVariantGetPtrIndexedGetter
	VariantGetPtrKeyedSetter GDExtensionInterfaceVariantGetPtrKeyedSetter
	VariantGetPtrKeyedGetter GDExtensionInterfaceVariantGetPtrKeyedGetter
	VariantGetPtrKeyedChecker GDExtensionInterfaceVariantGetPtrKeyedChecker
	VariantGetConstantValue GDExtensionInterfaceVariantGetConstantValue
	VariantGetPtrUtilityFunction GDExtensionInterfaceVariantGetPtrUtilityFunction
	StringNewWithLatin1Chars GDExtensionInterfaceStringNewWithLatin1Chars
	StringNewWithUtf8Chars GDExtensionInterfaceStringNewWithUtf8Chars
	StringNewWithUtf16Chars GDExtensionInterfaceStringNewWithUtf16Chars
	StringNewWithUtf32Chars GDExtensionInterfaceStringNewWithUtf32Chars
	StringNewWithWideChars GDExtensionInterfaceStringNewWithWideChars
	StringNewWithLatin1CharsAndLen GDExtensionInterfaceStringNewWithLatin1CharsAndLen
	StringNewWithUtf8CharsAndLen GDExtensionInterfaceStringNewWithUtf8CharsAndLen
	StringNewWithUtf8CharsAndLen2 GDExtensionInterfaceStringNewWithUtf8CharsAndLen2
	StringNewWithUtf16CharsAndLen GDExtensionInterfaceStringNewWithUtf16CharsAndLen
	StringNewWithUtf16CharsAndLen2 GDExtensionInterfaceStringNewWithUtf16CharsAndLen2
	StringNewWithUtf32CharsAndLen GDExtensionInterfaceStringNewWithUtf32CharsAndLen
	StringNewWithWideCharsAndLen GDExtensionInterfaceStringNewWithWideCharsAndLen
	StringToLatin1Chars GDExtensionInterfaceStringToLatin1Chars
	StringToUtf8Chars GDExtensionInterfaceStringToUtf8Chars
	StringToUtf16Chars GDExtensionInterfaceStringToUtf16Chars
	StringToUtf32Chars GDExtensionInterfaceStringToUtf32Chars
	StringToWideChars GDExtensionInterfaceStringToWideChars
	StringOperatorIndex GDExtensionInterfaceStringOperatorIndex
	StringOperatorIndexConst GDExtensionInterfaceStringOperatorIndexConst
	StringOperatorPlusEqString GDExtensionInterfaceStringOperatorPlusEqString
	StringOperatorPlusEqChar GDExtensionInterfaceStringOperatorPlusEqChar
	StringOperatorPlusEqCstr GDExtensionInterfaceStringOperatorPlusEqCstr
	StringOperatorPlusEqWcstr GDExtensionInterfaceStringOperatorPlusEqWcstr
	StringOperatorPlusEqC32str GDExtensionInterfaceStringOperatorPlusEqC32str
	StringResize GDExtensionInterfaceStringResize
	StringNameNewWithLatin1Chars GDExtensionInterfaceStringNameNewWithLatin1Chars
	StringNameNewWithUtf8Chars GDExtensionInterfaceStringNameNewWithUtf8Chars
	StringNameNewWithUtf8CharsAndLen GDExtensionInterfaceStringNameNewWithUtf8CharsAndLen
	XmlParserOpenBuffer GDExtensionInterfaceXmlParserOpenBuffer
	FileAccessStoreBuffer GDExtensionInterfaceFileAccessStoreBuffer
	FileAccessGetBuffer GDExtensionInterfaceFileAccessGetBuffer
	ImagePtrw GDExtensionInterfaceImagePtrw
	ImagePtr GDExtensionInterfaceImagePtr
	WorkerThreadPoolAddNativeGroupTask GDExtensionInterfaceWorkerThreadPoolAddNativeGroupTask
	WorkerThreadPoolAddNativeTask GDExtensionInterfaceWorkerThreadPoolAddNativeTask
	PackedByteArrayOperatorIndex GDExtensionInterfacePackedByteArrayOperatorIndex
	PackedByteArrayOperatorIndexConst GDExtensionInterfacePackedByteArrayOperatorIndexConst
	PackedFloat32ArrayOperatorIndex GDExtensionInterfacePackedFloat32ArrayOperatorIndex
	PackedFloat32ArrayOperatorIndexConst GDExtensionInterfacePackedFloat32ArrayOperatorIndexConst
	PackedFloat64ArrayOperatorIndex GDExtensionInterfacePackedFloat64ArrayOperatorIndex
	PackedFloat64ArrayOperatorIndexConst GDExtensionInterfacePackedFloat64ArrayOperatorIndexConst
	PackedInt32ArrayOperatorIndex GDExtensionInterfacePackedInt32ArrayOperatorIndex
	PackedInt32ArrayOperatorIndexConst GDExtensionInterfacePackedInt32ArrayOperatorIndexConst
	PackedInt64ArrayOperatorIndex GDExtensionInterfacePackedInt64ArrayOperatorIndex
	PackedInt64ArrayOperatorIndexConst GDExtensionInterfacePackedInt64ArrayOperatorIndexConst
	PackedStringArrayOperatorIndex GDExtensionInterfacePackedStringArrayOperatorIndex
	PackedStringArrayOperatorIndexConst GDExtensionInterfacePackedStringArrayOperatorIndexConst
	PackedVector2ArrayOperatorIndex GDExtensionInterfacePackedVector2ArrayOperatorIndex
	PackedVector2ArrayOperatorIndexConst GDExtensionInterfacePackedVector2ArrayOperatorIndexConst
	PackedVector3ArrayOperatorIndex GDExtensionInterfacePackedVector3ArrayOperatorIndex
	PackedVector3ArrayOperatorIndexConst GDExtensionInterfacePackedVector3ArrayOperatorIndexConst
	PackedVector4ArrayOperatorIndex GDExtensionInterfacePackedVector4ArrayOperatorIndex
	PackedVector4ArrayOperatorIndexConst GDExtensionInterfacePackedVector4ArrayOperatorIndexConst
	PackedColorArrayOperatorIndex GDExtensionInterfacePackedColorArrayOperatorIndex
	PackedColorArrayOperatorIndexConst GDExtensionInterfacePackedColorArrayOperatorIndexConst
	ArrayOperatorIndex GDExtensionInterfaceArrayOperatorIndex
	ArrayOperatorIndexConst GDExtensionInterfaceArrayOperatorIndexConst
	ArrayRef GDExtensionInterfaceArrayRef
	ArraySetTyped GDExtensionInterfaceArraySetTyped
	DictionaryOperatorIndex GDExtensionInterfaceDictionaryOperatorIndex
	DictionaryOperatorIndexConst GDExtensionInterfaceDictionaryOperatorIndexConst
	ObjectMethodBindCall GDExtensionInterfaceObjectMethodBindCall
	ObjectMethodBindPtrcall GDExtensionInterfaceObjectMethodBindPtrcall
	ObjectDestroy GDExtensionInterfaceObjectDestroy
	GlobalGetSingleton GDExtensionInterfaceGlobalGetSingleton
	ObjectGetInstanceBinding GDExtensionInterfaceObjectGetInstanceBinding
	ObjectSetInstanceBinding GDExtensionInterfaceObjectSetInstanceBinding
	ObjectFreeInstanceBinding GDExtensionInterfaceObjectFreeInstanceBinding
	ObjectSetInstance GDExtensionInterfaceObjectSetInstance
	ObjectGetClassName GDExtensionInterfaceObjectGetClassName
	ObjectCastTo GDExtensionInterfaceObjectCastTo
	ObjectGetInstanceFromId GDExtensionInterfaceObjectGetInstanceFromId
	ObjectGetInstanceId GDExtensionInterfaceObjectGetInstanceId
	ObjectHasScriptMethod GDExtensionInterfaceObjectHasScriptMethod
	ObjectCallScriptMethod GDExtensionInterfaceObjectCallScriptMethod
	RefGetObject GDExtensionInterfaceRefGetObject
	RefSetObject GDExtensionInterfaceRefSetObject
	ScriptInstanceCreate GDExtensionInterfaceScriptInstanceCreate
	ScriptInstanceCreate2 GDExtensionInterfaceScriptInstanceCreate2
	ScriptInstanceCreate3 GDExtensionInterfaceScriptInstanceCreate3
	PlaceHolderScriptInstanceCreate GDExtensionInterfacePlaceHolderScriptInstanceCreate
	PlaceHolderScriptInstanceUpdate GDExtensionInterfacePlaceHolderScriptInstanceUpdate
	ObjectGetScriptInstance GDExtensionInterfaceObjectGetScriptInstance
	CallableCustomCreate GDExtensionInterfaceCallableCustomCreate
	CallableCustomCreate2 GDExtensionInterfaceCallableCustomCreate2
	CallableCustomGetUserData GDExtensionInterfaceCallableCustomGetUserData
	ClassdbConstructObject GDExtensionInterfaceClassdbConstructObject
	ClassdbGetMethodBind GDExtensionInterfaceClassdbGetMethodBind
	ClassdbGetClassTag GDExtensionInterfaceClassdbGetClassTag
	ClassdbRegisterExtensionClass GDExtensionInterfaceClassdbRegisterExtensionClass
	ClassdbRegisterExtensionClass2 GDExtensionInterfaceClassdbRegisterExtensionClass2
	ClassdbRegisterExtensionClass3 GDExtensionInterfaceClassdbRegisterExtensionClass3
	ClassdbRegisterExtensionClassMethod GDExtensionInterfaceClassdbRegisterExtensionClassMethod
	ClassdbRegisterExtensionClassVirtualMethod GDExtensionInterfaceClassdbRegisterExtensionClassVirtualMethod
	ClassdbRegisterExtensionClassIntegerConstant GDExtensionInterfaceClassdbRegisterExtensionClassIntegerConstant
	ClassdbRegisterExtensionClassProperty GDExtensionInterfaceClassdbRegisterExtensionClassProperty
	ClassdbRegisterExtensionClassPropertyIndexed GDExtensionInterfaceClassdbRegisterExtensionClassPropertyIndexed
	ClassdbRegisterExtensionClassPropertyGroup GDExtensionInterfaceClassdbRegisterExtensionClassPropertyGroup
	ClassdbRegisterExtensionClassPropertySubgroup GDExtensionInterfaceClassdbRegisterExtensionClassPropertySubgroup
	ClassdbRegisterExtensionClassSignal GDExtensionInterfaceClassdbRegisterExtensionClassSignal
	ClassdbUnregisterExtensionClass GDExtensionInterfaceClassdbUnregisterExtensionClass
	GetLibraryPath GDExtensionInterfaceGetLibraryPath
	EditorAddPlugin GDExtensionInterfaceEditorAddPlugin
	EditorRemovePlugin GDExtensionInterfaceEditorRemovePlugin
	}

func (x *GDExtensionInterface) loadProcAddresses() {
	x.GetGodotVersion = (GDExtensionInterfaceGetGodotVersion)(dlsymGD("get_godot_version"))
	x.MemAlloc = (GDExtensionInterfaceMemAlloc)(dlsymGD("mem_alloc"))
	x.MemRealloc = (GDExtensionInterfaceMemRealloc)(dlsymGD("mem_realloc"))
	x.MemFree = (GDExtensionInterfaceMemFree)(dlsymGD("mem_free"))
	x.PrintError = (GDExtensionInterfacePrintError)(dlsymGD("print_error"))
	x.PrintErrorWithMessage = (GDExtensionInterfacePrintErrorWithMessage)(dlsymGD("print_error_with_message"))
	x.PrintWarning = (GDExtensionInterfacePrintWarning)(dlsymGD("print_warning"))
	x.PrintWarningWithMessage = (GDExtensionInterfacePrintWarningWithMessage)(dlsymGD("print_warning_with_message"))
	x.PrintScriptError = (GDExtensionInterfacePrintScriptError)(dlsymGD("print_script_error"))
	x.PrintScriptErrorWithMessage = (GDExtensionInterfacePrintScriptErrorWithMessage)(dlsymGD("print_script_error_with_message"))
	x.GetNativeStructSize = (GDExtensionInterfaceGetNativeStructSize)(dlsymGD("get_native_struct_size"))
	x.VariantNewCopy = (GDExtensionInterfaceVariantNewCopy)(dlsymGD("variant_new_copy"))
	x.VariantNewNil = (GDExtensionInterfaceVariantNewNil)(dlsymGD("variant_new_nil"))
	x.VariantDestroy = (GDExtensionInterfaceVariantDestroy)(dlsymGD("variant_destroy"))
	x.VariantCall = (GDExtensionInterfaceVariantCall)(dlsymGD("variant_call"))
	x.VariantCallStatic = (GDExtensionInterfaceVariantCallStatic)(dlsymGD("variant_call_static"))
	x.VariantEvaluate = (GDExtensionInterfaceVariantEvaluate)(dlsymGD("variant_evaluate"))
	x.VariantSet = (GDExtensionInterfaceVariantSet)(dlsymGD("variant_set"))
	x.VariantSetNamed = (GDExtensionInterfaceVariantSetNamed)(dlsymGD("variant_set_named"))
	x.VariantSetKeyed = (GDExtensionInterfaceVariantSetKeyed)(dlsymGD("variant_set_keyed"))
	x.VariantSetIndexed = (GDExtensionInterfaceVariantSetIndexed)(dlsymGD("variant_set_indexed"))
	x.VariantGet = (GDExtensionInterfaceVariantGet)(dlsymGD("variant_get"))
	x.VariantGetNamed = (GDExtensionInterfaceVariantGetNamed)(dlsymGD("variant_get_named"))
	x.VariantGetKeyed = (GDExtensionInterfaceVariantGetKeyed)(dlsymGD("variant_get_keyed"))
	x.VariantGetIndexed = (GDExtensionInterfaceVariantGetIndexed)(dlsymGD("variant_get_indexed"))
	x.VariantIterInit = (GDExtensionInterfaceVariantIterInit)(dlsymGD("variant_iter_init"))
	x.VariantIterNext = (GDExtensionInterfaceVariantIterNext)(dlsymGD("variant_iter_next"))
	x.VariantIterGet = (GDExtensionInterfaceVariantIterGet)(dlsymGD("variant_iter_get"))
	x.VariantHash = (GDExtensionInterfaceVariantHash)(dlsymGD("variant_hash"))
	x.VariantRecursiveHash = (GDExtensionInterfaceVariantRecursiveHash)(dlsymGD("variant_recursive_hash"))
	x.VariantHashCompare = (GDExtensionInterfaceVariantHashCompare)(dlsymGD("variant_hash_compare"))
	x.VariantBooleanize = (GDExtensionInterfaceVariantBooleanize)(dlsymGD("variant_booleanize"))
	x.VariantDuplicate = (GDExtensionInterfaceVariantDuplicate)(dlsymGD("variant_duplicate"))
	x.VariantStringify = (GDExtensionInterfaceVariantStringify)(dlsymGD("variant_stringify"))
	x.VariantGetType = (GDExtensionInterfaceVariantGetType)(dlsymGD("variant_get_type"))
	x.VariantHasMethod = (GDExtensionInterfaceVariantHasMethod)(dlsymGD("variant_has_method"))
	x.VariantHasMember = (GDExtensionInterfaceVariantHasMember)(dlsymGD("variant_has_member"))
	x.VariantHasKey = (GDExtensionInterfaceVariantHasKey)(dlsymGD("variant_has_key"))
	x.VariantGetTypeName = (GDExtensionInterfaceVariantGetTypeName)(dlsymGD("variant_get_type_name"))
	x.VariantCanConvert = (GDExtensionInterfaceVariantCanConvert)(dlsymGD("variant_can_convert"))
	x.VariantCanConvertStrict = (GDExtensionInterfaceVariantCanConvertStrict)(dlsymGD("variant_can_convert_strict"))
	x.GetVariantFromTypeConstructor = (GDExtensionInterfaceGetVariantFromTypeConstructor)(dlsymGD("get_variant_from_type_constructor"))
	x.GetVariantToTypeConstructor = (GDExtensionInterfaceGetVariantToTypeConstructor)(dlsymGD("get_variant_to_type_constructor"))
	x.VariantGetPtrOperatorEvaluator = (GDExtensionInterfaceVariantGetPtrOperatorEvaluator)(dlsymGD("variant_get_ptr_operator_evaluator"))
	x.VariantGetPtrBuiltinMethod = (GDExtensionInterfaceVariantGetPtrBuiltinMethod)(dlsymGD("variant_get_ptr_builtin_method"))
	x.VariantGetPtrConstructor = (GDExtensionInterfaceVariantGetPtrConstructor)(dlsymGD("variant_get_ptr_constructor"))
	x.VariantGetPtrDestructor = (GDExtensionInterfaceVariantGetPtrDestructor)(dlsymGD("variant_get_ptr_destructor"))
	x.VariantConstruct = (GDExtensionInterfaceVariantConstruct)(dlsymGD("variant_construct"))
	x.VariantGetPtrSetter = (GDExtensionInterfaceVariantGetPtrSetter)(dlsymGD("variant_get_ptr_setter"))
	x.VariantGetPtrGetter = (GDExtensionInterfaceVariantGetPtrGetter)(dlsymGD("variant_get_ptr_getter"))
	x.VariantGetPtrIndexedSetter = (GDExtensionInterfaceVariantGetPtrIndexedSetter)(dlsymGD("variant_get_ptr_indexed_setter"))
	x.VariantGetPtrIndexedGetter = (GDExtensionInterfaceVariantGetPtrIndexedGetter)(dlsymGD("variant_get_ptr_indexed_getter"))
	x.VariantGetPtrKeyedSetter = (GDExtensionInterfaceVariantGetPtrKeyedSetter)(dlsymGD("variant_get_ptr_keyed_setter"))
	x.VariantGetPtrKeyedGetter = (GDExtensionInterfaceVariantGetPtrKeyedGetter)(dlsymGD("variant_get_ptr_keyed_getter"))
	x.VariantGetPtrKeyedChecker = (GDExtensionInterfaceVariantGetPtrKeyedChecker)(dlsymGD("variant_get_ptr_keyed_checker"))
	x.VariantGetConstantValue = (GDExtensionInterfaceVariantGetConstantValue)(dlsymGD("variant_get_constant_value"))
	x.VariantGetPtrUtilityFunction = (GDExtensionInterfaceVariantGetPtrUtilityFunction)(dlsymGD("variant_get_ptr_utility_function"))
	x.StringNewWithLatin1Chars = (GDExtensionInterfaceStringNewWithLatin1Chars)(dlsymGD("string_new_with_latin1_chars"))
	x.StringNewWithUtf8Chars = (GDExtensionInterfaceStringNewWithUtf8Chars)(dlsymGD("string_new_with_utf8_chars"))
	x.StringNewWithUtf16Chars = (GDExtensionInterfaceStringNewWithUtf16Chars)(dlsymGD("string_new_with_utf16_chars"))
	x.StringNewWithUtf32Chars = (GDExtensionInterfaceStringNewWithUtf32Chars)(dlsymGD("string_new_with_utf32_chars"))
	x.StringNewWithWideChars = (GDExtensionInterfaceStringNewWithWideChars)(dlsymGD("string_new_with_wide_chars"))
	x.StringNewWithLatin1CharsAndLen = (GDExtensionInterfaceStringNewWithLatin1CharsAndLen)(dlsymGD("string_new_with_latin1_chars_and_len"))
	x.StringNewWithUtf8CharsAndLen = (GDExtensionInterfaceStringNewWithUtf8CharsAndLen)(dlsymGD("string_new_with_utf8_chars_and_len"))
	x.StringNewWithUtf8CharsAndLen2 = (GDExtensionInterfaceStringNewWithUtf8CharsAndLen2)(dlsymGD("string_new_with_utf8_chars_and_len2"))
	x.StringNewWithUtf16CharsAndLen = (GDExtensionInterfaceStringNewWithUtf16CharsAndLen)(dlsymGD("string_new_with_utf16_chars_and_len"))
	x.StringNewWithUtf16CharsAndLen2 = (GDExtensionInterfaceStringNewWithUtf16CharsAndLen2)(dlsymGD("string_new_with_utf16_chars_and_len2"))
	x.StringNewWithUtf32CharsAndLen = (GDExtensionInterfaceStringNewWithUtf32CharsAndLen)(dlsymGD("string_new_with_utf32_chars_and_len"))
	x.StringNewWithWideCharsAndLen = (GDExtensionInterfaceStringNewWithWideCharsAndLen)(dlsymGD("string_new_with_wide_chars_and_len"))
	x.StringToLatin1Chars = (GDExtensionInterfaceStringToLatin1Chars)(dlsymGD("string_to_latin1_chars"))
	x.StringToUtf8Chars = (GDExtensionInterfaceStringToUtf8Chars)(dlsymGD("string_to_utf8_chars"))
	x.StringToUtf16Chars = (GDExtensionInterfaceStringToUtf16Chars)(dlsymGD("string_to_utf16_chars"))
	x.StringToUtf32Chars = (GDExtensionInterfaceStringToUtf32Chars)(dlsymGD("string_to_utf32_chars"))
	x.StringToWideChars = (GDExtensionInterfaceStringToWideChars)(dlsymGD("string_to_wide_chars"))
	x.StringOperatorIndex = (GDExtensionInterfaceStringOperatorIndex)(dlsymGD("string_operator_index"))
	x.StringOperatorIndexConst = (GDExtensionInterfaceStringOperatorIndexConst)(dlsymGD("string_operator_index_const"))
	x.StringOperatorPlusEqString = (GDExtensionInterfaceStringOperatorPlusEqString)(dlsymGD("string_operator_plus_eq_string"))
	x.StringOperatorPlusEqChar = (GDExtensionInterfaceStringOperatorPlusEqChar)(dlsymGD("string_operator_plus_eq_char"))
	x.StringOperatorPlusEqCstr = (GDExtensionInterfaceStringOperatorPlusEqCstr)(dlsymGD("string_operator_plus_eq_cstr"))
	x.StringOperatorPlusEqWcstr = (GDExtensionInterfaceStringOperatorPlusEqWcstr)(dlsymGD("string_operator_plus_eq_wcstr"))
	x.StringOperatorPlusEqC32str = (GDExtensionInterfaceStringOperatorPlusEqC32str)(dlsymGD("string_operator_plus_eq_c32str"))
	x.StringResize = (GDExtensionInterfaceStringResize)(dlsymGD("string_resize"))
	x.StringNameNewWithLatin1Chars = (GDExtensionInterfaceStringNameNewWithLatin1Chars)(dlsymGD("string_name_new_with_latin1_chars"))
	x.StringNameNewWithUtf8Chars = (GDExtensionInterfaceStringNameNewWithUtf8Chars)(dlsymGD("string_name_new_with_utf8_chars"))
	x.StringNameNewWithUtf8CharsAndLen = (GDExtensionInterfaceStringNameNewWithUtf8CharsAndLen)(dlsymGD("string_name_new_with_utf8_chars_and_len"))
	x.XmlParserOpenBuffer = (GDExtensionInterfaceXmlParserOpenBuffer)(dlsymGD("xml_parser_open_buffer"))
	x.FileAccessStoreBuffer = (GDExtensionInterfaceFileAccessStoreBuffer)(dlsymGD("file_access_store_buffer"))
	x.FileAccessGetBuffer = (GDExtensionInterfaceFileAccessGetBuffer)(dlsymGD("file_access_get_buffer"))
	x.ImagePtrw = (GDExtensionInterfaceImagePtrw)(dlsymGD("image_ptrw"))
	x.ImagePtr = (GDExtensionInterfaceImagePtr)(dlsymGD("image_ptr"))
	x.WorkerThreadPoolAddNativeGroupTask = (GDExtensionInterfaceWorkerThreadPoolAddNativeGroupTask)(dlsymGD("worker_thread_pool_add_native_group_task"))
	x.WorkerThreadPoolAddNativeTask = (GDExtensionInterfaceWorkerThreadPoolAddNativeTask)(dlsymGD("worker_thread_pool_add_native_task"))
	x.PackedByteArrayOperatorIndex = (GDExtensionInterfacePackedByteArrayOperatorIndex)(dlsymGD("packed_byte_array_operator_index"))
	x.PackedByteArrayOperatorIndexConst = (GDExtensionInterfacePackedByteArrayOperatorIndexConst)(dlsymGD("packed_byte_array_operator_index_const"))
	x.PackedFloat32ArrayOperatorIndex = (GDExtensionInterfacePackedFloat32ArrayOperatorIndex)(dlsymGD("packed_float32_array_operator_index"))
	x.PackedFloat32ArrayOperatorIndexConst = (GDExtensionInterfacePackedFloat32ArrayOperatorIndexConst)(dlsymGD("packed_float32_array_operator_index_const"))
	x.PackedFloat64ArrayOperatorIndex = (GDExtensionInterfacePackedFloat64ArrayOperatorIndex)(dlsymGD("packed_float32_array_operator_index"))
	x.PackedFloat64ArrayOperatorIndexConst = (GDExtensionInterfacePackedFloat64ArrayOperatorIndexConst)(dlsymGD("packed_float32_array_operator_index_const"))
	x.PackedInt32ArrayOperatorIndex = (GDExtensionInterfacePackedInt32ArrayOperatorIndex)(dlsymGD("packed_int32_array_operator_index"))
	x.PackedInt32ArrayOperatorIndexConst = (GDExtensionInterfacePackedInt32ArrayOperatorIndexConst)(dlsymGD("packed_int32_array_operator_index_const"))
	x.PackedInt64ArrayOperatorIndex = (GDExtensionInterfacePackedInt64ArrayOperatorIndex)(dlsymGD("packed_int64_array_operator_index"))
	x.PackedInt64ArrayOperatorIndexConst = (GDExtensionInterfacePackedInt64ArrayOperatorIndexConst)(dlsymGD("packed_int64_array_operator_index_const"))
	x.PackedStringArrayOperatorIndex = (GDExtensionInterfacePackedStringArrayOperatorIndex)(dlsymGD("packed_string_array_operator_index"))
	x.PackedStringArrayOperatorIndexConst = (GDExtensionInterfacePackedStringArrayOperatorIndexConst)(dlsymGD("packed_string_array_operator_index_const"))
	x.PackedVector2ArrayOperatorIndex = (GDExtensionInterfacePackedVector2ArrayOperatorIndex)(dlsymGD("packed_vector2_array_operator_index"))
	x.PackedVector2ArrayOperatorIndexConst = (GDExtensionInterfacePackedVector2ArrayOperatorIndexConst)(dlsymGD("packed_vector2_array_operator_index_const"))
	x.PackedVector3ArrayOperatorIndex = (GDExtensionInterfacePackedVector3ArrayOperatorIndex)(dlsymGD("packed_vector3_array_operator_index"))
	x.PackedVector3ArrayOperatorIndexConst = (GDExtensionInterfacePackedVector3ArrayOperatorIndexConst)(dlsymGD("packed_vector3_array_operator_index_const"))
	x.PackedVector4ArrayOperatorIndex = (GDExtensionInterfacePackedVector4ArrayOperatorIndex)(dlsymGD("packed_vector4_array_operator_index"))
	x.PackedVector4ArrayOperatorIndexConst = (GDExtensionInterfacePackedVector4ArrayOperatorIndexConst)(dlsymGD("packed_vector4_array_operator_index_const"))
	x.PackedColorArrayOperatorIndex = (GDExtensionInterfacePackedColorArrayOperatorIndex)(dlsymGD("packed_color_array_operator_index"))
	x.PackedColorArrayOperatorIndexConst = (GDExtensionInterfacePackedColorArrayOperatorIndexConst)(dlsymGD("packed_color_array_operator_index_const"))
	x.ArrayOperatorIndex = (GDExtensionInterfaceArrayOperatorIndex)(dlsymGD("array_operator_index"))
	x.ArrayOperatorIndexConst = (GDExtensionInterfaceArrayOperatorIndexConst)(dlsymGD("array_operator_index_const"))
	x.ArrayRef = (GDExtensionInterfaceArrayRef)(dlsymGD("array_ref"))
	x.ArraySetTyped = (GDExtensionInterfaceArraySetTyped)(dlsymGD("array_set_typed"))
	x.DictionaryOperatorIndex = (GDExtensionInterfaceDictionaryOperatorIndex)(dlsymGD("dictionary_operator_index"))
	x.DictionaryOperatorIndexConst = (GDExtensionInterfaceDictionaryOperatorIndexConst)(dlsymGD("dictionary_operator_index_const"))
	x.ObjectMethodBindCall = (GDExtensionInterfaceObjectMethodBindCall)(dlsymGD("object_method_bind_call"))
	x.ObjectMethodBindPtrcall = (GDExtensionInterfaceObjectMethodBindPtrcall)(dlsymGD("object_method_bind_ptrcall"))
	x.ObjectDestroy = (GDExtensionInterfaceObjectDestroy)(dlsymGD("object_destroy"))
	x.GlobalGetSingleton = (GDExtensionInterfaceGlobalGetSingleton)(dlsymGD("global_get_singleton"))
	x.ObjectGetInstanceBinding = (GDExtensionInterfaceObjectGetInstanceBinding)(dlsymGD("object_get_instance_binding"))
	x.ObjectSetInstanceBinding = (GDExtensionInterfaceObjectSetInstanceBinding)(dlsymGD("object_set_instance_binding"))
	x.ObjectFreeInstanceBinding = (GDExtensionInterfaceObjectFreeInstanceBinding)(dlsymGD("object_free_instance_binding"))
	x.ObjectSetInstance = (GDExtensionInterfaceObjectSetInstance)(dlsymGD("object_set_instance"))
	x.ObjectGetClassName = (GDExtensionInterfaceObjectGetClassName)(dlsymGD("object_get_class_name"))
	x.ObjectCastTo = (GDExtensionInterfaceObjectCastTo)(dlsymGD("object_cast_to"))
	x.ObjectGetInstanceFromId = (GDExtensionInterfaceObjectGetInstanceFromId)(dlsymGD("object_get_instance_from_id"))
	x.ObjectGetInstanceId = (GDExtensionInterfaceObjectGetInstanceId)(dlsymGD("object_get_instance_id"))
	x.ObjectHasScriptMethod = (GDExtensionInterfaceObjectHasScriptMethod)(dlsymGD("object_has_script_method"))
	x.ObjectCallScriptMethod = (GDExtensionInterfaceObjectCallScriptMethod)(dlsymGD("object_call_script_method"))
	x.RefGetObject = (GDExtensionInterfaceRefGetObject)(dlsymGD("ref_get_object"))
	x.RefSetObject = (GDExtensionInterfaceRefSetObject)(dlsymGD("ref_set_object"))
	x.ScriptInstanceCreate = (GDExtensionInterfaceScriptInstanceCreate)(dlsymGD("script_instance_create"))
	x.ScriptInstanceCreate2 = (GDExtensionInterfaceScriptInstanceCreate2)(dlsymGD("script_instance_create2"))
	x.ScriptInstanceCreate3 = (GDExtensionInterfaceScriptInstanceCreate3)(dlsymGD("script_instance_create3"))
	x.PlaceHolderScriptInstanceCreate = (GDExtensionInterfacePlaceHolderScriptInstanceCreate)(dlsymGD("placeholder_script_instance_create"))
	x.PlaceHolderScriptInstanceUpdate = (GDExtensionInterfacePlaceHolderScriptInstanceUpdate)(dlsymGD("placeholder_script_instance_update"))
	x.ObjectGetScriptInstance = (GDExtensionInterfaceObjectGetScriptInstance)(dlsymGD("object_get_script_instance"))
	x.CallableCustomCreate = (GDExtensionInterfaceCallableCustomCreate)(dlsymGD("callable_custom_create"))
	x.CallableCustomCreate2 = (GDExtensionInterfaceCallableCustomCreate2)(dlsymGD("callable_custom_create2"))
	x.CallableCustomGetUserData = (GDExtensionInterfaceCallableCustomGetUserData)(dlsymGD("callable_custom_get_user_data"))
	x.ClassdbConstructObject = (GDExtensionInterfaceClassdbConstructObject)(dlsymGD("classdb_construct_object"))
	x.ClassdbGetMethodBind = (GDExtensionInterfaceClassdbGetMethodBind)(dlsymGD("classdb_get_method_bind"))
	x.ClassdbGetClassTag = (GDExtensionInterfaceClassdbGetClassTag)(dlsymGD("classdb_get_class_tag"))
	x.ClassdbRegisterExtensionClass = (GDExtensionInterfaceClassdbRegisterExtensionClass)(dlsymGD("classdb_register_extension_class"))
	x.ClassdbRegisterExtensionClass2 = (GDExtensionInterfaceClassdbRegisterExtensionClass2)(dlsymGD("classdb_register_extension_class2"))
	x.ClassdbRegisterExtensionClass3 = (GDExtensionInterfaceClassdbRegisterExtensionClass3)(dlsymGD("classdb_register_extension_class3"))
	x.ClassdbRegisterExtensionClassMethod = (GDExtensionInterfaceClassdbRegisterExtensionClassMethod)(dlsymGD("classdb_register_extension_class_method"))
	x.ClassdbRegisterExtensionClassVirtualMethod = (GDExtensionInterfaceClassdbRegisterExtensionClassVirtualMethod)(dlsymGD("classdb_register_extension_class_virtual_method"))
	x.ClassdbRegisterExtensionClassIntegerConstant = (GDExtensionInterfaceClassdbRegisterExtensionClassIntegerConstant)(dlsymGD("classdb_register_extension_class_integer_constant"))
	x.ClassdbRegisterExtensionClassProperty = (GDExtensionInterfaceClassdbRegisterExtensionClassProperty)(dlsymGD("classdb_register_extension_class_property"))
	x.ClassdbRegisterExtensionClassPropertyIndexed = (GDExtensionInterfaceClassdbRegisterExtensionClassPropertyIndexed)(dlsymGD("classdb_register_extension_class_property_indexed"))
	x.ClassdbRegisterExtensionClassPropertyGroup = (GDExtensionInterfaceClassdbRegisterExtensionClassPropertyGroup)(dlsymGD("classdb_register_extension_class_property_group"))
	x.ClassdbRegisterExtensionClassPropertySubgroup = (GDExtensionInterfaceClassdbRegisterExtensionClassPropertySubgroup)(dlsymGD("classdb_register_extension_class_property_subgroup"))
	x.ClassdbRegisterExtensionClassSignal = (GDExtensionInterfaceClassdbRegisterExtensionClassSignal)(dlsymGD("classdb_register_extension_class_signal"))
	x.ClassdbUnregisterExtensionClass = (GDExtensionInterfaceClassdbUnregisterExtensionClass)(dlsymGD("classdb_unregister_extension_class"))
	x.GetLibraryPath = (GDExtensionInterfaceGetLibraryPath)(dlsymGD("get_library_path"))
	x.EditorAddPlugin = (GDExtensionInterfaceEditorAddPlugin)(dlsymGD("editor_add_plugin"))
	x.EditorRemovePlugin = (GDExtensionInterfaceEditorRemovePlugin)(dlsymGD("editor_remove_plugin"))
	}


