/*
------------------------------------------------------------------------------
//   This code was generated by template ffi_gdextension_interface.go.tmpl.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "ffi_gdextension_interface.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------
*/
package api

import "unsafe"

var (
	FFI GDExtensionInterface
)

type GDExtensionInterface struct {
	GetProcAddress                                func(p_function_name string) unsafe.Pointer
	GetGodotVersion                               func(r_godot_version unsafe.Pointer)
	MemAlloc                                      func(p_bytes int64) unsafe.Pointer
	MemRealloc                                    func(p_ptr unsafe.Pointer, p_bytes int64) unsafe.Pointer
	MemFree                                       func(p_ptr unsafe.Pointer)
	PrintError                                    func(p_description string, p_function string, p_file string, p_line int32, p_editor_notify bool)
	PrintErrorWithMessage                         func(p_description string, p_message string, p_function string, p_file string, p_line int32, p_editor_notify bool)
	PrintWarning                                  func(p_description string, p_function string, p_file string, p_line int32, p_editor_notify bool)
	PrintWarningWithMessage                       func(p_description string, p_message string, p_function string, p_file string, p_line int32, p_editor_notify bool)
	PrintScriptError                              func(p_description string, p_function string, p_file string, p_line int32, p_editor_notify bool)
	PrintScriptErrorWithMessage                   func(p_description string, p_message string, p_function string, p_file string, p_line int32, p_editor_notify bool)
	GetNativeStructSize                           func(p_name unsafe.Pointer) uint64
	VariantNewCopy                                func(r_dest unsafe.Pointer, p_src unsafe.Pointer)
	VariantNewNil                                 func(r_dest unsafe.Pointer)
	VariantDestroy                                func(p_self unsafe.Pointer)
	VariantCall                                   func(p_self unsafe.Pointer, p_method unsafe.Pointer, p_args unsafe.Pointer, p_argument_count int64, r_return unsafe.Pointer, r_error unsafe.Pointer)
	VariantCallStatic                             func(p_type uint32 /*VariantType*/, p_method unsafe.Pointer, p_args unsafe.Pointer, p_argument_count int64, r_return unsafe.Pointer, r_error unsafe.Pointer)
	VariantEvaluate                               func(p_op uint32 /*VariantOperator*/, p_a unsafe.Pointer, p_b unsafe.Pointer, r_return unsafe.Pointer, r_valid unsafe.Pointer)
	VariantSet                                    func(p_self unsafe.Pointer, p_key unsafe.Pointer, p_value unsafe.Pointer, r_valid unsafe.Pointer)
	VariantSetNamed                               func(p_self unsafe.Pointer, p_key unsafe.Pointer, p_value unsafe.Pointer, r_valid unsafe.Pointer)
	VariantSetKeyed                               func(p_self unsafe.Pointer, p_key unsafe.Pointer, p_value unsafe.Pointer, r_valid unsafe.Pointer)
	VariantSetIndexed                             func(p_self unsafe.Pointer, p_index int64, p_value unsafe.Pointer, r_valid unsafe.Pointer, r_oob unsafe.Pointer)
	VariantGet                                    func(p_self unsafe.Pointer, p_key unsafe.Pointer, r_ret unsafe.Pointer, r_valid unsafe.Pointer)
	VariantGetNamed                               func(p_self unsafe.Pointer, p_key unsafe.Pointer, r_ret unsafe.Pointer, r_valid unsafe.Pointer)
	VariantGetKeyed                               func(p_self unsafe.Pointer, p_key unsafe.Pointer, r_ret unsafe.Pointer, r_valid unsafe.Pointer)
	VariantGetIndexed                             func(p_self unsafe.Pointer, p_index int64, r_ret unsafe.Pointer, r_valid unsafe.Pointer, r_oob unsafe.Pointer)
	VariantIterInit                               func(p_self unsafe.Pointer, r_iter unsafe.Pointer, r_valid unsafe.Pointer) bool
	VariantIterNext                               func(p_self unsafe.Pointer, r_iter unsafe.Pointer, r_valid unsafe.Pointer) bool
	VariantIterGet                                func(p_self unsafe.Pointer, r_iter unsafe.Pointer, r_ret unsafe.Pointer, r_valid unsafe.Pointer)
	VariantHash                                   func(p_self unsafe.Pointer) int64
	VariantRecursiveHash                          func(p_self unsafe.Pointer, p_recursion_count int64) int64
	VariantHashCompare                            func(p_self unsafe.Pointer, p_other unsafe.Pointer) bool
	VariantBooleanize                             func(p_self unsafe.Pointer) bool
	VariantDuplicate                              func(p_self unsafe.Pointer, r_ret unsafe.Pointer, p_deep bool)
	VariantStringify                              func(p_self unsafe.Pointer, r_ret unsafe.Pointer)
	VariantGetType                                func(p_self unsafe.Pointer) uint32 /*VariantType*/
	VariantHasMethod                              func(p_self unsafe.Pointer, p_method unsafe.Pointer) bool
	VariantHasMember                              func(p_type uint32 /*VariantType*/, p_member unsafe.Pointer) bool
	VariantHasKey                                 func(p_self unsafe.Pointer, p_key unsafe.Pointer, r_valid unsafe.Pointer) bool
	VariantGetTypeName                            func(p_type uint32 /*VariantType*/, r_name unsafe.Pointer)
	VariantCanConvert                             func(p_from uint32 /*VariantType*/, p_to uint32 /*VariantType*/) bool
	VariantCanConvertStrict                       func(p_from uint32 /*VariantType*/, p_to uint32 /*VariantType*/) bool
	GetVariantFromTypeConstructor                 func(p_type uint32 /*VariantType*/) GDExtensionVariantFromTypeConstructorFunc
	GetVariantToTypeConstructor                   func(p_type uint32 /*VariantType*/) GDExtensionTypeFromVariantConstructorFunc
	VariantGetPtrOperatorEvaluator                func(p_operator uint32 /*VariantOperator*/, p_type_a uint32 /*VariantType*/, p_type_b uint32 /*VariantType*/) GDExtensionPtrOperatorEvaluator
	VariantGetPtrBuiltinMethod                    func(p_type uint32 /*VariantType*/, p_method unsafe.Pointer, p_hash int64) GDExtensionPtrBuiltInMethod
	VariantGetPtrConstructor                      func(p_type uint32 /*VariantType*/, p_constructor int32) GDExtensionPtrConstructor
	VariantGetPtrDestructor                       func(p_type uint32 /*VariantType*/) GDExtensionPtrDestructor
	VariantConstruct                              func(p_type uint32 /*VariantType*/, r_base unsafe.Pointer, p_args unsafe.Pointer, p_argument_count int32, r_error unsafe.Pointer)
	VariantGetPtrSetter                           func(p_type uint32 /*VariantType*/, p_member unsafe.Pointer) GDExtensionPtrSetter
	VariantGetPtrGetter                           func(p_type uint32 /*VariantType*/, p_member unsafe.Pointer) GDExtensionPtrGetter
	VariantGetPtrIndexedSetter                    func(p_type uint32 /*VariantType*/) GDExtensionPtrIndexedSetter
	VariantGetPtrIndexedGetter                    func(p_type uint32 /*VariantType*/) GDExtensionPtrIndexedGetter
	VariantGetPtrKeyedSetter                      func(p_type uint32 /*VariantType*/) GDExtensionPtrKeyedSetter
	VariantGetPtrKeyedGetter                      func(p_type uint32 /*VariantType*/) GDExtensionPtrKeyedGetter
	VariantGetPtrKeyedChecker                     func(p_type uint32 /*VariantType*/) GDExtensionPtrKeyedChecker
	VariantGetConstantValue                       func(p_type uint32 /*VariantType*/, p_constant unsafe.Pointer, r_ret unsafe.Pointer)
	VariantGetPtrUtilityFunction                  func(p_function unsafe.Pointer, p_hash int64) GDExtensionPtrUtilityFunction
	StringNewWithLatin1Chars                      func(r_dest unsafe.Pointer, p_contents string)
	StringNewWithUtf8Chars                        func(r_dest unsafe.Pointer, p_contents string)
	StringNewWithUtf16Chars                       func(r_dest unsafe.Pointer, p_contents unsafe.Pointer)
	StringNewWithUtf32Chars                       func(r_dest unsafe.Pointer, p_contents unsafe.Pointer)
	StringNewWithWideChars                        func(r_dest unsafe.Pointer, p_contents unsafe.Pointer)
	StringNewWithLatin1CharsAndLen                func(r_dest unsafe.Pointer, p_contents string, p_size int64)
	StringNewWithUtf8CharsAndLen                  func(r_dest unsafe.Pointer, p_contents string, p_size int64)
	StringNewWithUtf8CharsAndLen2                 func(r_dest unsafe.Pointer, p_contents string, p_size int64) int64
	StringNewWithUtf16CharsAndLen                 func(r_dest unsafe.Pointer, p_contents unsafe.Pointer, p_char_count int64)
	StringNewWithUtf16CharsAndLen2                func(r_dest unsafe.Pointer, p_contents unsafe.Pointer, p_char_count int64, p_default_little_endian bool) int64
	StringNewWithUtf32CharsAndLen                 func(r_dest unsafe.Pointer, p_contents unsafe.Pointer, p_char_count int64)
	StringNewWithWideCharsAndLen                  func(r_dest unsafe.Pointer, p_contents unsafe.Pointer, p_char_count int64)
	StringToLatin1Chars                           func(p_self unsafe.Pointer, r_text unsafe.Pointer, p_max_write_length int64) int64
	StringToUtf8Chars                             func(p_self unsafe.Pointer, r_text unsafe.Pointer, p_max_write_length int64) int64
	StringToUtf16Chars                            func(p_self unsafe.Pointer, r_text unsafe.Pointer, p_max_write_length int64) int64
	StringToUtf32Chars                            func(p_self unsafe.Pointer, r_text unsafe.Pointer, p_max_write_length int64) int64
	StringToWideChars                             func(p_self unsafe.Pointer, r_text unsafe.Pointer, p_max_write_length int64) int64
	StringOperatorIndex                           func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	StringOperatorIndexConst                      func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	StringOperatorPlusEqString                    func(p_self unsafe.Pointer, p_b unsafe.Pointer)
	StringOperatorPlusEqChar                      func(p_self unsafe.Pointer, p_b rune)
	StringOperatorPlusEqCstr                      func(p_self unsafe.Pointer, p_b string)
	StringOperatorPlusEqWcstr                     func(p_self unsafe.Pointer, p_b unsafe.Pointer)
	StringOperatorPlusEqC32str                    func(p_self unsafe.Pointer, p_b unsafe.Pointer)
	StringResize                                  func(p_self unsafe.Pointer, p_resize int64) int64
	StringNameNewWithLatin1Chars                  func(r_dest unsafe.Pointer, p_contents string, p_is_static bool)
	StringNameNewWithUtf8Chars                    func(r_dest unsafe.Pointer, p_contents string)
	StringNameNewWithUtf8CharsAndLen              func(r_dest unsafe.Pointer, p_contents string, p_size int64)
	XmlParserOpenBuffer                           func(p_instance unsafe.Pointer, p_buffer unsafe.Pointer, p_size int64) int64
	FileAccessStoreBuffer                         func(p_instance unsafe.Pointer, p_src unsafe.Pointer, p_length uint64)
	FileAccessGetBuffer                           func(p_instance unsafe.Pointer, p_dst unsafe.Pointer, p_length uint64) uint64
	ImagePtrw                                     func(p_instance unsafe.Pointer) unsafe.Pointer
	ImagePtr                                      func(p_instance unsafe.Pointer) unsafe.Pointer
	WorkerThreadPoolAddNativeGroupTask            func(p_instance unsafe.Pointer, p_func unsafe.Pointer /*void(*p_func)(void * ,uint32_t)*/, p_userdata unsafe.Pointer, p_elements int, p_tasks int, p_high_priority bool, p_description unsafe.Pointer) int64
	WorkerThreadPoolAddNativeTask                 func(p_instance unsafe.Pointer, p_func unsafe.Pointer /*void(*p_func)(void * )*/, p_userdata unsafe.Pointer, p_high_priority bool, p_description unsafe.Pointer) int64
	PackedByteArrayOperatorIndex                  func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedByteArrayOperatorIndexConst             func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedFloat32ArrayOperatorIndex               func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedFloat32ArrayOperatorIndexConst          func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedFloat64ArrayOperatorIndex               func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedFloat64ArrayOperatorIndexConst          func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedInt32ArrayOperatorIndex                 func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedInt32ArrayOperatorIndexConst            func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedInt64ArrayOperatorIndex                 func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedInt64ArrayOperatorIndexConst            func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedStringArrayOperatorIndex                func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedStringArrayOperatorIndexConst           func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedVector2ArrayOperatorIndex               func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedVector2ArrayOperatorIndexConst          func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedVector3ArrayOperatorIndex               func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedVector3ArrayOperatorIndexConst          func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedVector4ArrayOperatorIndex               func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedVector4ArrayOperatorIndexConst          func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedColorArrayOperatorIndex                 func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	PackedColorArrayOperatorIndexConst            func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	ArrayOperatorIndex                            func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	ArrayOperatorIndexConst                       func(p_self unsafe.Pointer, p_index int64) unsafe.Pointer
	ArrayRef                                      func(p_self unsafe.Pointer, p_from unsafe.Pointer)
	ArraySetTyped                                 func(p_self unsafe.Pointer, p_type uint32 /*VariantType*/, p_class_name unsafe.Pointer, p_script unsafe.Pointer)
	DictionaryOperatorIndex                       func(p_self unsafe.Pointer, p_key unsafe.Pointer) unsafe.Pointer
	DictionaryOperatorIndexConst                  func(p_self unsafe.Pointer, p_key unsafe.Pointer) unsafe.Pointer
	ObjectMethodBindCall                          func(p_method_bind unsafe.Pointer, p_instance unsafe.Pointer, p_args unsafe.Pointer, p_arg_count int64, r_ret unsafe.Pointer, r_error unsafe.Pointer)
	ObjectMethodBindPtrcall                       func(p_method_bind unsafe.Pointer, p_instance unsafe.Pointer, p_args unsafe.Pointer, r_ret unsafe.Pointer)
	ObjectDestroy                                 func(p_o unsafe.Pointer)
	GlobalGetSingleton                            func(p_name unsafe.Pointer) unsafe.Pointer
	ObjectGetInstanceBinding                      func(p_o unsafe.Pointer, p_token unsafe.Pointer, p_callbacks unsafe.Pointer) unsafe.Pointer
	ObjectSetInstanceBinding                      func(p_o unsafe.Pointer, p_token unsafe.Pointer, p_binding unsafe.Pointer, p_callbacks unsafe.Pointer)
	ObjectFreeInstanceBinding                     func(p_o unsafe.Pointer, p_token unsafe.Pointer)
	ObjectSetInstance                             func(p_o unsafe.Pointer, p_classname unsafe.Pointer, p_instance unsafe.Pointer)
	ObjectGetClassName                            func(p_object unsafe.Pointer, p_library unsafe.Pointer, r_class_name unsafe.Pointer) bool
	ObjectCastTo                                  func(p_object unsafe.Pointer, p_class_tag unsafe.Pointer) unsafe.Pointer
	ObjectGetInstanceFromId                       func(p_instance_id int64) unsafe.Pointer
	ObjectGetInstanceId                           func(p_object unsafe.Pointer) int64
	ObjectHasScriptMethod                         func(p_object unsafe.Pointer, p_method unsafe.Pointer) bool
	ObjectCallScriptMethod                        func(p_object unsafe.Pointer, p_method unsafe.Pointer, p_args unsafe.Pointer, p_argument_count int64, r_return unsafe.Pointer, r_error unsafe.Pointer)
	RefGetObject                                  func(p_ref unsafe.Pointer) unsafe.Pointer
	RefSetObject                                  func(p_ref unsafe.Pointer, p_object unsafe.Pointer)
	ScriptInstanceCreate                          func(p_info unsafe.Pointer, p_instance_data unsafe.Pointer) unsafe.Pointer
	ScriptInstanceCreate2                         func(p_info unsafe.Pointer, p_instance_data unsafe.Pointer) unsafe.Pointer
	ScriptInstanceCreate3                         func(p_info unsafe.Pointer, p_instance_data unsafe.Pointer) unsafe.Pointer
	PlaceHolderScriptInstanceCreate               func(p_language unsafe.Pointer, p_script unsafe.Pointer, p_owner unsafe.Pointer) unsafe.Pointer
	PlaceHolderScriptInstanceUpdate               func(p_placeholder unsafe.Pointer, p_properties unsafe.Pointer, p_values unsafe.Pointer)
	ObjectGetScriptInstance                       func(p_object unsafe.Pointer, p_language unsafe.Pointer) unsafe.Pointer
	CallableCustomCreate                          func(r_callable unsafe.Pointer, p_callable_custom_info unsafe.Pointer)
	CallableCustomCreate2                         func(r_callable unsafe.Pointer, p_callable_custom_info unsafe.Pointer)
	CallableCustomGetUserData                     func(p_callable unsafe.Pointer, p_token unsafe.Pointer) unsafe.Pointer
	ClassdbConstructObject                        func(p_classname unsafe.Pointer) unsafe.Pointer
	ClassdbGetMethodBind                          func(p_classname unsafe.Pointer, p_methodname unsafe.Pointer, p_hash int64) unsafe.Pointer
	ClassdbGetClassTag                            func(p_classname unsafe.Pointer) unsafe.Pointer
	ClassdbRegisterExtensionClass                 func(p_library unsafe.Pointer, p_class_name unsafe.Pointer, p_parent_class_name unsafe.Pointer, p_extension_funcs unsafe.Pointer)
	ClassdbRegisterExtensionClass2                func(p_library unsafe.Pointer, p_class_name unsafe.Pointer, p_parent_class_name unsafe.Pointer, p_extension_funcs unsafe.Pointer)
	ClassdbRegisterExtensionClass3                func(p_library unsafe.Pointer, p_class_name unsafe.Pointer, p_parent_class_name unsafe.Pointer, p_extension_funcs unsafe.Pointer)
	ClassdbRegisterExtensionClassMethod           func(p_library unsafe.Pointer, p_class_name unsafe.Pointer, p_method_info unsafe.Pointer)
	ClassdbRegisterExtensionClassVirtualMethod    func(p_library unsafe.Pointer, p_class_name unsafe.Pointer, p_method_info unsafe.Pointer)
	ClassdbRegisterExtensionClassIntegerConstant  func(p_library unsafe.Pointer, p_class_name unsafe.Pointer, p_enum_name unsafe.Pointer, p_constant_name unsafe.Pointer, p_constant_value int64, p_is_bitfield bool)
	ClassdbRegisterExtensionClassProperty         func(p_library unsafe.Pointer, p_class_name unsafe.Pointer, p_info unsafe.Pointer, p_setter unsafe.Pointer, p_getter unsafe.Pointer)
	ClassdbRegisterExtensionClassPropertyIndexed  func(p_library unsafe.Pointer, p_class_name unsafe.Pointer, p_info unsafe.Pointer, p_setter unsafe.Pointer, p_getter unsafe.Pointer, p_index int64)
	ClassdbRegisterExtensionClassPropertyGroup    func(p_library unsafe.Pointer, p_class_name unsafe.Pointer, p_group_name unsafe.Pointer, p_prefix unsafe.Pointer)
	ClassdbRegisterExtensionClassPropertySubgroup func(p_library unsafe.Pointer, p_class_name unsafe.Pointer, p_subgroup_name unsafe.Pointer, p_prefix unsafe.Pointer)
	ClassdbRegisterExtensionClassSignal           func(p_library unsafe.Pointer, p_class_name unsafe.Pointer, p_signal_name unsafe.Pointer, p_argument_info unsafe.Pointer, p_argument_count int64)
	ClassdbUnregisterExtensionClass               func(p_library unsafe.Pointer, p_class_name unsafe.Pointer)
	GetLibraryPath                                func(p_library unsafe.Pointer, r_path unsafe.Pointer)
	EditorAddPlugin                               func(p_class_name unsafe.Pointer)
	EditorRemovePlugin                            func(p_class_name unsafe.Pointer)
}
