/*
------------------------------------------------------------------------------
//   This code was generated by template ffi_gdextension_interface.go.tmpl.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "ffi_gdextension_interface.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------
*/
package gdx

//revive:disable

var (
	api GDExtensionInterface
)

type GDExtensionInterface struct {
	// All of the GDExtension interface functions.
}

func (x *GDExtensionInterface) loadProcAddresses() {
}
